/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pro_sistema_venta;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        super(" "+"MENU DE VENTAS");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCliente = new javax.swing.JMenu();
        MenuProducto = new javax.swing.JMenu();
        MenuInventario = new javax.swing.JMenu();
        MenuVenta = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        MenuCliente.setBackground(new java.awt.Color(0, 0, 0));
        MenuCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        MenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new_add_user_16734´nag.png"))); // NOI18N
        MenuCliente.setText("CLIENTE");
        MenuCliente.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MenuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuClienteMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuCliente);

        MenuProducto.setBackground(new java.awt.Color(51, 51, 51));
        MenuProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51)));
        MenuProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart_88980kasd.png"))); // NOI18N
        MenuProducto.setText("PRODUCTO");
        MenuProducto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MenuProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuProductoMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuProducto);

        MenuInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        MenuInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/document_write_22637sds.png"))); // NOI18N
        MenuInventario.setText("INVENTARIO");
        MenuInventario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MenuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuInventarioMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuInventario);

        MenuVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51)));
        MenuVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/business-economic-finance-interprise-point-of-services_88994weerewr.png"))); // NOI18N
        MenuVenta.setText("VENTA");
        MenuVenta.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        MenuVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuVentaMousePressed(evt);
            }
        });
        jMenuBar1.add(MenuVenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClienteMousePressed
       JRCliente a=new JRCliente();
       a.setVisible(true);
    }//GEN-LAST:event_MenuClienteMousePressed

    private void MenuProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProductoMousePressed
        JRProducto a=new JRProducto();
        a.setVisible(true);
    }//GEN-LAST:event_MenuProductoMousePressed

    private void MenuInventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInventarioMousePressed
        JRInventario a=new JRInventario();
        a.setVisible(true);
    }//GEN-LAST:event_MenuInventarioMousePressed

    private void MenuVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVentaMousePressed
        JRVenta a=new JRVenta();
        a.setVisible(true);
    }//GEN-LAST:event_MenuVentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCliente;
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JMenu MenuProducto;
    private javax.swing.JMenu MenuVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
